spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${OPENAI_API_MODEL}
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimension: 1536
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/sbdocs
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

key:
  api-key-header: ${API_KEY_HEADER}
  api-key: ${API_KEY}